version: "3"
services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    command:
      - /bin/sh
      - -c
      - |
        sh /app/entrypoint.sh
        yarn dev
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports: 
      - ${APP_PORT}:${APP_PORT}
    networks:
      - application
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment: 
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      TZ: Asia/Taipei
    ports: 
      - 3306:3306
    volumes: 
      - .:/ns-app
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - application
networks:
  application: